### ISSUE TITLE
0.9.5 Release Checklist

### ISSUE THREAD

**Issue by mbasaglia** [mbasaglia/Knotter#118]
- [x] No open bug issues
- [x] No open blocking issues
- [x] No \todo in the code that is not in an issue
- [x] #109 (Selecting edges) completed
- [x] #107 (Cusp / Edge style in script) completed
- [x] #95 (Import/Export from script) completed
- [x] Check plugin "requires" version
- [x] Include Russian translation from launchpad (and add the required doc -- main page & release notes)
- [x] Update British translation from launchpad
