### ISSUE TITLE
0.9.6 Release Checklist

### ISSUE THREAD

**Issue by mbasaglia** [mbasaglia/Knotter#135]
- [x] No open bug issues
- [x] No open blocking issues
- [x] Try to close or move all issues from 1.0 milestone
- [x] No \todo in the code that is not in an issue
- [x] Update Translations
- [x] Close #102 
- [x] Merge loose branches
