### ISSUE TITLE
0.9.0 Release checklist

### ISSUE THREAD

**Issue by mbasaglia** [mbasaglia/Knotter#55]
- [x] remove all debugging code
- [x] remove all \todos (do what is needed to be done or open a ticket)
- [x] close or move all the [issues](https://github.com/mbasaglia/Knotter/issues?milestone=1&state=open)
