### ISSUE TITLE
0.9.2 Release Checklist

### ISSUE THREAD

**Issue by mbasaglia** [mbasaglia/Knotter#71]
- [x] No open bug issues https://github.com/mbasaglia/Knotter/issues?labels=bug&milestone=4&page=1&state=open
- [x] No open blocking issues https://github.com/mbasaglia/Knotter/issues?labels=blocking&milestone=4&page=1&state=open
- [x] Issue #43 is closed
- [x] Scripting support being enabled/disabled and remember that across sections
- [x] Scripting Supports custom cusp shapes
- [x] Closed #78
