### ISSUE TITLE
0.9.3 Release Checklist

### ISSUE THREAD

**Issue by mbasaglia** [mbasaglia/Knotter#72]
- [x] No open bug issues https://github.com/mbasaglia/Knotter/issues?labels=bug&milestone=4&page=1&state=open
- [x] Scripting Supports Parametric insert
- [x] Plugin Insert Polygon
- [x] Plugin Insert square lattice  
- [x] #70 Closed
- [x] #59 Closed
