### ISSUE TITLE
0.9.4 Release Checklist

### ISSUE THREAD

**Issue by mbasaglia** [mbasaglia/Knotter#73]
- [x] No open bug issues https://github.com/mbasaglia/Knotter/issues?labels=bug&milestone=4&page=1&state=open
- [x] Updated 0.9.3 translations
- [ ] <del>Support to load plugins from local file</del>
- [x] Reload plugins
- [x] #81 closed
- [x] Plugin editor
- [x] Plugin _Insert Text_ implemented
- [x] Windows 32/64 build scripts
